### ISSUE TITLE
Wrap waveforms instead of truncating

### ISSUE THREAD

**Issue by askvortsov1** [janestreet/hardcaml_waveterm#2]
Lengthy waveforms that don't fit in the terminal/screen width can end up hard to read:

![image](https://user-images.githubusercontent.com/38059171/127428682-f43e012e-afc7-41a9-9e98-4f6e53e27c28.png)

This is a great use case for the interactive viewer, but there are probably cases where an ASCII expect test would still be useful to have. Have you considered wrapping excess content around to another "waveform block" below the first one? 

So instead of:

```
CLOCK: -_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

SIGNAL: -------------------------______________-----__________----__--_____________________-------------_________--------_________------_
```

the printed result could look somewhat like:

```
CLOCK:   -_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-

SIGNAL:  -------------------------______________-----__________----__--_________

==============================================================

CLOCK (cont): _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

SIGNAL (cont): ____________-------------_________--------_________------___--_

```

So instead of truncating waves beyond `display_width`, we'd just wrap them around to a second display.

**Comment by andrewray** [comment]
You can always `print` the waveform multiple times with different `start_offset`s.
